name: DebugBuild
on:
 push:
  branches:
    - master
env:
    # リポジトリのルートディレクトリを基点としたソリューションファイルのパス
    SOLUTION_FILE_PATH: project/CG2_05.sin
    # Visual Studio の構成(debug / Ralease)
    CONFIGURATION: Debug
jobs:
 build:
  runs-on: windows-2022
